# Generated by Django 3.1.4 on 2021-02-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20210220_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='songfile',
            name='file_size',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='songfile',
            name='image',
            field=models.ImageField(upload_to='audioimage/image'),
        ),
    ]
