# Generated by Django 3.1.4 on 2021-02-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20210223_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songfile',
            name='file_size',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
