# Generated by Django 3.1.4 on 2021-02-23 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_auto_20210223_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songfile',
            name='file_size',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
