# Generated by Django 3.1.4 on 2021-02-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_auto_20210223_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearclear',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='songfile',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
