# Generated by Django 3.1.4 on 2021-02-25 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_auto_20210225_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='songfile',
            name='file_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
