# Generated by Django 3.1.4 on 2021-02-25 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_songfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songfile',
            name='file_type',
            field=models.CharField(help_text="Example: '.wav'", max_length=10),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('songfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='page.songfile')),
            ],
        ),
    ]
