# Generated by Django 3.1.4 on 2021-02-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_auto_20210225_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='songfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='page.songfile'),
        ),
    ]
