# Generated by Django 3.1.4 on 2021-02-25 20:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_auto_20210225_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='songfile',
            field=models.ForeignKey(default=87, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='page.songfile'),
            preserve_default=False,
        ),
    ]
